language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
before_script:
- export DATABASE_URL=postgres://postgres@localhost/salesforce
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "salesforce";' -U postgres
install:
  - "pip install -r requirements/test.txt"
script:
  - ./salesforce/manage.py test salesforce
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: salesforce-dev
    qa: salesforce-qa
    prod: salesforce-prod
  on:
    repo: Hawk94/salesforce
  run:
    - "./salesforce/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true

cache: pip
